# Generated by Django 3.2.16 on 2022-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
